### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by AtikD** [drforse/aiogram_many_bots_lib#2]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\семья\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Atik\\Sublime Text\\src\\aiomanybots\\setup.py'"'"'; __file__='"'"'D:\\Atik\\Sublime Text\\src\\aiomanybots\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Семья\AppData\Local\Temp\pip-pip-egg-info-36h0czn_'
         cwd: D:\Atik\Sublime Text\src\aiomanybots\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Atik\Sublime Text\src\aiomanybots\setup.py", line 2, in <module>
        import aiomanybots
      File "D:\Atik\Sublime Text\src\aiomanybots\aiomanybots\__init__.py", line 1, in <module>
        from .core import AioBotsRunner
      File "D:\Atik\Sublime Text\src\aiomanybots\aiomanybots\core.py", line 4, in <module>
        from manybots import BotsRunner
    ModuleNotFoundError: No module named 'manybots'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by drforse** [comment]
please, try installing it now
